services:
  #find a way to tear this down after the init scripts has worked
  setup-meilisearch:
    build: ./tools/meilisearch-index-generator/
    command: ["/wait-for-it/wait-for-it.sh", "meilisearch:7700", "--", "make", "run-with-emulator"]
    depends_on:
      - meilisearch
    environment:
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_MASTER_KEY: meilisearch-master-key
    volumes:
      - ./scripts/wait-for-it/:/wait-for-it

  meilisearch:
    image: getmeili/meilisearch:v1.9
    volumes:
      - ./data.ms:/data.ms
    environment:
      MEILI_MASTER_KEY: meilisearch-master-key
    ports:
      - 7700:7700

  api:
    build: ./api
    depends_on:
      - setup-meilisearch
    environment:
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_MASTER_KEY: meilisearch-master-key
    ports:
      - 8811:8811

  frontend:
    build: ./frontend
    depends_on:
      - api
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8811
      REACT_ENV: development
    ports:
       - 3000:3000
