name: Build meilisearch setup image

on:
  push:
    branches:
      - main
    paths:
      - tools/meilisearch-index-generator/**
      - .github/workflows/build-meilisearch-setup-image.yaml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-meilisearch-setup

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./tools/meilisearch-index-generator

          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
